export enum actions {
    AUTHORIZE = 'AUTHORIZE',
    ADD_TIMER = 'ADD_TIMER',
    REMOVE_TIMER = 'REMOVE_TIMER',
    REMOVE_ALL_TIMERS = 'REMOVE_ALL_TIMERS',
    SET_TIME = 'SET_TIME',
    SWITCH_THEME = 'SWITCH_THEME'
}